### ISSUE TITLE
PUT request to upload the iso never finishes

### ISSUE THREAD

**Issue by sammcj** [xenserver/packer-plugin-citrixhypervisor#21]
Sits here forever:

```
systems-samm ~/src/github.com/rdobson/packer-builder-xenserver/examples % packer build centos-6.6.json
xenserver-iso output will be in this color.

==> xenserver-iso: XAPI client session established
==> xenserver-iso: Downloading or copying ISO
    xenserver-iso: Downloading or copying: http://centos.mirror.serversaustralia.com.au/6.6/isos/x86_64/CentOS-6.6-x86_64-minimal.iso
==> xenserver-iso: Starting HTTP server on port 8000
==> xenserver-iso: Step: Upload VDI 'CentOS-6.6-x86_64-minimal.iso'
==> xenserver-iso: PUT 'https://s1-dl360-01/import_raw_vdi?session_id=OpaqueRef%3A75b48216-2034-aa42-7a71-f3851fde3cb9&task_id=OpaqueRef%3A3fd254c0-412b-e363-d3fe-d29cb50ab6da&vdi=OpaqueRef%3A864e8a33-a30e-1166-0631-6c09fe328af7'
```

But I can see the .iso appear in XenCentre:

![screen shot 2015-02-10 at 13 01 37](https://cloud.githubusercontent.com/assets/862951/6120071/fa85794a-b124-11e4-9ada-8305db2bce29.png)
- Config is the same as example on readme
- XenServer 6.5
- Fresh build of packer-dev and packer-builder-xenserver as per instructions
- go version go1.4.1 darwin/amd64

**Comment by rdobson** [comment]
HI @sammcj,

Thanks for raising this - it's a known problem - sorry for not forewarning you! Unfortunately as we developed this plugin we exposed a bug in how XAPI handled disk uploads (which we use for importing the ISO). We've fixed this, but it's only available in our dev builds of XenServer, available here:
http://xenserver.org/overview-xenserver-open-source-virtualization/download/2-uncategorised/115-development-snapshots.html

The PR's where here:
https://github.com/xapi-project/xen-api/pull/2052
https://github.com/xapi-project/vhd-tool/pull/15

(FYI - If you rounded your ISO to the nearest 2MB you would work around this issue, but clearly that's neither nice nor practical!).

Thanks.

**Comment by sammcj** [comment]
Thanks for the reply - do you know when this will be available as a patch / update? We run 22 physical hosts, all on XenServer 6.5 and I don't really want to start installing dev builds.

I've also heard that XenServer (Citrix) may also be working on an official(ish) packer plugin.

**Comment by rdobson** [comment]
Hi @sammcj,

This is the official plugin - there is an effort downstream by @xenserverarmy, but Tim is looking to upstream his changes.

The patches for 'full' support will be pulled into the next XenServer release/service pack, so please stay tuned for that. In the mean time, I've created the '6.x-support' branch:
https://github.com/rdobson/packer-builder-xenserver/tree/6.x-support

Which allows you to run packer against a 6.x box. This unfortunately doesn't allow you to either upload ISOs (they need to be on an ISO SR) or use a Floppy - but pretty much everything else should work.

The code is currently being tested, but feel free to have a play.
